name: Continuous Monitoring of Dockerhub and Public ECR
on: push
#  schedule:
#    - cron: "*/5 * * * *"

jobs:
  monitor-ecr:
    name: Monitor Dockerhub and Public ECR
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Public ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws

      - name: Authenticate and pull an image from public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker pull public.ecr.aws/xray/aws-xray-daemon:latest

      - name: Publish metrics on pulling an image
        if: ${{ always() }}
        run: |
          if [[ "$(docker images -q public.ecr.aws/xray/aws-xray-daemon:latest11> /dev/null)" == "" ]]; then
            aws cloudwatch put-metric-data --metric-name PullImageFailureFromECR --dimensions test=fail --namespace MonitorDaemon --value 0 --timestamp $(date +%s)
          else
            echo "hi!"
            aws cloudwatch put-metric-data --metric-name PullImageFailureFromECR --dimensions test=fail --namespace MonitorDaemon --value 1 --timestamp $(date +%s)
          fi
